class BasicSubmission(object):
    def __init__(self, form_answers):
        self.name = form_answers.get("name")
        self.age = form_answers.get("age")
        self.gender = form_answers.get("gender")
        self.race = form_answers.get("race")
        self.state = form_answers.get("state")
        self.edu = form_answers.get("edu")
        self.discord = form_answers.get("discord")
        self.media = form_answers.get("media")
        self.investingtime = form_answers.get("investingtime")
        self.followers = form_answers.get("followers")
        self.contenttime = form_answers.get("contenttime")
        self.postcount = form_answers.get("postcount")
        self.ppw = form_answers.get("ppw")
        self.lastpostdate = form_answers.get("lastpostdate")
        self.charts_displays = form_answers.get("charts_displays")
        self.screenrec = form_answers.get("screenrec")
        self.qanda = form_answers.get("qanda")
        self.livetrading = form_answers.get("livetrading")
        self.avgpostlength = form_answers.get("avgpostlength")

    def PrintAll(self):
        print(self.name)
        print(self.age)
        print(self.gender)
        print(self.race)
        print(self.state)
        print(self.edu)
        print(self.discord)
        print(self.media)
        print(self.investingtime)
        print(self.followers)
        print(self.contenttime)
        print(self.postcount)
        print(self.ppw)
        print(self.lastpostdate)
        print(self.charts_displays)
        print(self.screenrec)
        print(self.qanda)
        print(self.livetrading)
        print(self.avgpostlength)
